
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jy3694/venv/venv_pt/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 5.19.0-50-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jy3694/venv/venv_pt/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 5.19.0-50-generic - x86_64
...
